#1 - Installing Bootstrap to hello_world app pt 1
https://www.notion.so/Get-started-with-Django-Part-1-fb5e472d20c345859e9c3dad81fdbd69#235d5189fcc3405a93b9ed9c7be95270

Full set of commands (hyper.is):
```bash

Microsoft Windows [Version 10.0.18363.1139]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\droid>cd django-start/django-start

C:\Users\droid\django-start\django-start>python3 -m venv venv

C:\Users\droid\django-start\django-start>venv\Scripts\activate.bat

(venv) C:\Users\droid\django-start\django-start>python manage.py runserver

(venv) C:\Users\droid\django-start\django-start>

(venv) C:\Users\droid\django-start\django-start>cd hello_world

(venv) C:\Users\droid\django-start\django-start\hello_world>urls.py

(venv) C:\Users\droid\django-start\django-start\hello_world>
[main 2020-10-21T08:23:33.246Z] update#setState idle
(node:16232) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\droid\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\vscode-sqlite3\build\Release\sqlite.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:16232) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\droid\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
(node:8868) Electron: Loading non-context-aware native module in renderer: '\\?\C:\Users\droid\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\spdlog\build\Release\spdlog.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
[main 2020-10-21T08:24:03.247Z] update#setState checking for updates
[main 2020-10-21T08:24:03.469Z] update#setState idle

(venv) C:\Users\droid\django-start\django-start\hello_world>cd ../

(venv) C:\Users\droid\django-start\django-start>python manage.py runserver

(venv) C:\Users\droid\django-start\django-start>cd personal_portfolio

(venv) C:\Users\droid\django-start\django-start\personal_portfolio>mkdir templates

(venv) C:\Users\droid\django-start\django-start\personal_portfolio>cd templates

(venv) C:\Users\droid\django-start\django-start\personal_portfolio\templates>cd ../

(venv) C:\Users\droid\django-start\django-start\personal_portfolio>cd ../

(venv) C:\Users\droid\django-start\django-start>cd hello_world

(venv) C:\Users\droid\django-start\django-start\hello_world>cd templates

(venv) C:\Users\droid\django-start\django-start\hello_world\templates>hello_world.html

(venv) C:\Users\droid\django-start\django-start\hello_world\templates>

```

#2 - Installing git commands:
```bash

Microsoft Windows [Version 10.0.18363.1139]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\droid>choco install git
Chocolatey v0.10.15
[Pending] Removing incomplete install for 'git.install'
Installing the following packages:
git
By installing you accept licenses for the packages.

git.install v2.28.0 [Approved]
git.install package files install completed. Performing other installation steps.
The package git.install wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): y

Using Git LFS
Installing 64-bit git.install...
git.install has been installed.
git.install installed to 'C:\Program Files\Git'
  git.install can be automatically uninstalled.
 The install of git.install was successful.
  Software installed to 'C:\Program Files\Git\'

git v2.28.0 [Approved]
git package files install completed. Performing other installation steps.
 The install of git was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 2/2 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

C:\Users\droid>git
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone             Clone a repository into a new directory
   init              Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add               Add file contents to the index
   mv                Move or rename a file, a directory, or a symlink
   restore           Restore working tree files
   rm                Remove files from the working tree and from the index
   sparse-checkout   Initialize and modify the sparse-checkout

examine the history and state (see also: git help revisions)
   bisect            Use binary search to find the commit that introduced a bug
   diff              Show changes between commits, commit and working tree, etc
   grep              Print lines matching a pattern
   log               Show commit logs
   show              Show various types of objects
   status            Show the working tree status

grow, mark and tweak your common history
   branch            List, create, or delete branches
   commit            Record changes to the repository
   merge             Join two or more development histories together
   rebase            Reapply commits on top of another base tip
   reset             Reset current HEAD to the specified state
   switch            Switch branches
   tag               Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch             Download objects and refs from another repository
   pull              Fetch from and integrate with another repository or a local branch
   push              Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
See 'git help git' for an overview of the system.

C:\Users\droid>git config
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    --worktree            use per-worktree config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color           find the color configured: slot [default]
    --get-colorbool       find the color setting: slot [stdout-is-tty]

Type
    -t, --type <>         value is given this type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)
    --expiry-date         value is an expiry date

Other
    -z, --null            terminate values with NUL byte
    --name-only           show variable names only
    --includes            respect include directives on lookup
    --show-origin         show origin of config (file, standard input, blob, command line)
    --show-scope          show scope of config (worktree, local, global, system, command)
    --default <value>     with --get, use default value when missing entry

C:\Users\droid>git config --global
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    --worktree            use per-worktree config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color           find the color configured: slot [default]
    --get-colorbool       find the color setting: slot [stdout-is-tty]

Type
    -t, --type <>         value is given this type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)
    --expiry-date         value is an expiry date

Other
    -z, --null            terminate values with NUL byte
    --name-only           show variable names only
    --includes            respect include directives on lookup
    --show-origin         show origin of config (file, standard input, blob, command line)
    --show-scope          show scope of config (worktree, local, global, system, command)
    --default <value>     with --get, use default value when missing entry

C:\Users\droid>git config --global user.name "LArbuckle"

C:\Users\droid>git config --global user.email liam@acordsoftware.tech

C:\Users\droid>git config --global core.editor C:\Users\droid\AppData\Local\Programs\Microsoft VS Code\code.exe
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    --worktree            use per-worktree config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color           find the color configured: slot [default]
    --get-colorbool       find the color setting: slot [stdout-is-tty]

Type
    -t, --type <>         value is given this type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)
    --expiry-date         value is an expiry date

Other
    -z, --null            terminate values with NUL byte
    --name-only           show variable names only
    --includes            respect include directives on lookup
    --show-origin         show origin of config (file, standard input, blob, command line)
    --show-scope          show scope of config (worktree, local, global, system, command)
    --default <value>     with --get, use default value when missing entry

C:\Users\droid>git config --global core.editor "'C:\Users\droid\AppData\Local\Programs\Microsoft VS Code' -multiInst -notabbar -nosession -noPlugin"

C:\Users\droid>git config --global init.defaultBranch main

C:\Users\droid>git config --list
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=LArbuckle
user.email=liam@acordsoftware.tech
core.editor='C:\Users\droid\AppData\Local\Programs\Microsoft VS Code' -multiInst -notabbar -nosession -noPlugin
init.defaultbranch=main

C:\Users\droid>git config user.name
LArbuckle

C:\Users\droid>cd C:/Users/droid/my_project
The system cannot find the path specified.

C:\Users\droid>C:/Users/droid/myproject
'C:/Users/droid/myproject' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\droid>cd c:/Users/droid/myproject

c:\Users\droid\myproject>git init
Initialized empty Git repository in C:/Users/droid/myproject/.git/

c:\Users\droid\myproject>git add *c
fatal: pathspec '*c' did not match any files

c:\Users\droid\myproject>git add *.c
fatal: pathspec '*.c' did not match any files

c:\Users\droid\myproject>git add LICENSE
fatal: pathspec 'LICENSE' did not match any files

c:\Users\droid\myproject>git add *c
fatal: pathspec '*c' did not match any files

c:\Users\droid\myproject>git add file.txt

c:\Users\droid\myproject>git commit -m 'Initial Project Version'
error: pathspec 'Project' did not match any file(s) known to git
error: pathspec 'Version'' did not match any file(s) known to git

c:\Users\droid\myproject>git commit -m
error: switch `m' requires a value

c:\Users\droid\myproject>git commit -m 'InitialProjectVersion'
[main (root-commit) e9b0073] 'InitialProjectVersion'
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 file.txt

c:\Users\droid\myproject>git clone https://github.com/libgit2/libgit2
Cloning into 'libgit2'...
remote: Enumerating objects: 106467, done.
remote: Counting objects: 100% (106467/106467), done.
remote: Compressing objects: 100% (29234/29234), done.
remote: Total 106467 (delta 75311), reused 106464 (delta 75308), pack-reused 0
Receiving objects: 100% (106467/106467), 53.45 MiB | 739.00 KiB/s, done.
Resolving deltas: 100% (75311/75311), done.
Updating files: 100% (10822/10822), done.

c:\Users\droid\myproject>cd ../

c:\Users\droid>
```

Co-Authored-By: Liam Arbuckle <allianceofdroidsla@gmail.com>